/home/trentonbricken/anaconda3/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Process Process-22:
Traceback (most recent call last):
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/pyglet/gl/lib.py", line 149, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/pyglet/gl/lib_glx.py", line 46, in <module>
    glu_lib = pyglet.lib.load_library('GLU')
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/pyglet/lib.py", line 164, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trentonbricken/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/trentonbricken/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "org_traincontroller.py", line 106, in slave_routine
    r_queue.put((s_id, r_gen.rollout(params, rand_env_seed)))
  File "/home/trentonbricken/fem/utils/misc.py", line 213, in rollout
    obs = self.env.reset()
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 25, in reset
    return self.env.reset(**kwargs)
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 314, in reset
    return self.step(None)[0]
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 326, in step
    self.state = self.render("state_pixels")
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/gym/envs/box2d/car_racing.py", line 349, in render
    from gym.envs.classic_control import rendering
  File "/home/trentonbricken/anaconda3/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 32, in <module>
    ''')
ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
    
